#!/bin/sh

# Pre-push script that amends formatting of go-code

if [ "$( goimports -l . )" ]; then
	echo Updating the formatting of go
	find . -name "*.go" | xargs goimports -w
	git commit -a --amend --no-edit
fi

exit 0
